apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: ${KUBEDB_NAMESPACE}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${KUBEDB_CERT_NAME}
  namespace: ${KUBEDB_NAMESPACE}
spec:
  # Secret names are always required.
  secretName: ${KUBEDB_CERT_NAME}
  # TODO: How does kubedb handle cert regens?
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  # At least one of a DNS Name, URI, Email Address, or IP address is required.
  dnsNames:
  - ${KUBEDB_OPERATOR_NAME}
  - ${KUBEDB_OPERATOR_NAME}.${KUBEDB_NAMESPACE}.svc
  # Issuer references are always required.
  issuerRef:
    name: selfsigned-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
